[package]
name = "excaLibur"
version = "0.1"
lean_version = "leanprover-community/lean:3.19.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib.git", rev = "7c9a86d4750a2c86132c9fc69400646c88817fdb"}
